### PR TITLE
Clarify behavior of x87 FP registers in inline assembly

### PR DESCRIPTION
**Pull request by Amanieu**
This came up in a discussion on Zulip.

cc @joshtriplett

### CODE REVIEW

**Comment by joshtriplett** [comment]
Can you clarify and spell out how the writer of an `asm!` block can clobber all x87 registers? Do they need to write out a clobber for each register individually? You wrote `st(*)` here; someone might expect that syntax to work. Does it, or could it?

**Comment by Amanieu** [comment]
All 8 registers need to be explicitly clobbered, there is no wildcard syntax. The reason for this is that in the future we may decide to support x87 registers as proper operands. Also there is no precedent for a wildcard register name that covers multiple real registers.

**Comment by joshtriplett** [comment]
> Also there is no precedent for a wildcard register name that covers multiple real registers.

In theory we could do that with something like `clobber_abi("x87")`, but perhaps that's not worth catering for.

**Review by joshtriplett — APPROVED** [review]

**Comment by loveJesus** [comment]
Happy Easter and hello thanks for your work on rust. I am trying to implement the following in the new `asm!` syntax but i'm not really sure particularly about how to go about having the `fstp` command store into a rust variable. Thank you!
 
```rust
#[inline(always)]
pub fn cos_chirho(a: f32) -> f32 { 
let mut res: f32 = unsafe { mem::uninitialized() };

unsafe { asm!(
    r##"
        flds $1;
        fcos;
        fstps $0;
    "##
    : "=*m"(&mut res as *mut f32)
    : "*m"(&a as *const f32)
) };

res
}
```

**Comment by Amanieu** [comment]
Just pass the memory address in a `reg` and then use it as normal:
```rust
asm!(
	"flds [{}]",
	"fcos",
	"fstps [{}]",
	in(reg) &a
	in(reg) &mut res,
);
```

**Comment by loveJesus** [comment]
God is good! thank you.
Changed the `flds` to `fld dword ptr` and likewise for `fstp`. It works! 

I did not know however to use an `in(reg)` instead of `out(reg)` for the `&mut` parameter. It was giving me `(exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)` when it would compile with `out(reg) *&mut`. It makes sense that an `in` can work since we modify the contents pointed to by the register and not the register itself. Sorry to have bothered you with this. Do you think me attempting to make a pull request with this example would be helpful?

**Comment by Amanieu** [comment]
Rust-by-example might be a better place for some example code.

**Pull request merged**
