### PR TITLE
Document thiscall abi

### PR DESCRIPTION
**Pull request by DrMeepster**
Tracking issue: rust-lang/rust#42202

@rustbot label +S-waiting-on-stabilization

### CODE REVIEW

**Review by ehuss — APPROVED** [review]
Thanks!

**Comment by ehuss** [comment]
@DrMeepster It looks like there are conflicts, and it looks like maybe the "Allow edits and access to secrets by maintainers" option was unset which prevents me from fixing it. Can you rebase and fix the conflicts?

**Comment by DrMeepster** [comment]
Conflict resolved. Nice to see `thiscall` finally stabilized.

**Review by ehuss — APPROVED** [review]
Thanks!

**Pull request merged**
