### PR TITLE
Changes for unsafe extern blocks (RFC 3484)

### PR DESCRIPTION
**Pull request by spastorino**
This goes after this is merged:

- https://github.com/rust-lang/rust/pull/127921

...and CI should be happy after that.

I'd say that also this is kind of WIP until someone wouldn't mind fixing my broken english :).

r? @traviscross 

Tracking:

- https://github.com/rust-lang/rust/issues/123743

### CODE REVIEW

**Review by traviscross — APPROVED** [review]
Reviewed and pushed some changes.  It looks good to me.  We'll merge after...

- https://github.com/rust-lang/rust/pull/127921

...is merged.

**Comment by ehuss** [comment]
I pushed some updates here. The major change is to update the grammar, as it should be documenting the pre-validation grammar (since that is what is used for macros).

**Comment by ehuss** [comment]
I'll also note that this includes 2024 edition content. I kinda wanted to avoid that, since it is not yet stabilized. I may pull that out into a separate PR before merging this to hold to our process of not documenting unstable features.

**Comment by spastorino** [comment]
@traviscross @ehuss this is now ready as https://github.com/rust-lang/rust/pull/127921 is merged. I've rebased and retriggered CI tests and CI is happy now.

**Review by ehuss — APPROVED** [review]
Thanks!

I have removed the 2024 changes, which will be added back when 2024 stabilizes. I'll post a PR for that here shortly.

**Pull request merged**
