### PR TITLE
Add LoongArch to inline-assembly documentation

### PR DESCRIPTION
**Pull request by heiher**
This PR is a sub-part of https://github.com/rust-lang/rust/pull/111235, to move LoongArch from unstable to stable inline-assembly documentation.

### CODE REVIEW

**Review by Amanieu — APPROVED** [review]

**Comment by Amanieu** [comment]
This will be merged once FCP for stabilization passes.

**Comment by heiher** [comment]
I'm sorry, I make a minor change after your approved.

**Review by Amanieu — APPROVED** [review]

**Comment by Amanieu** [comment]
FCP is now complete, this can be merged.

**Review by ehuss — APPROVED** [review]
Thanks!

**Pull request merged**
