### PR TITLE
apply #950 to STYLE.md

### PR DESCRIPTION
**Pull request by ben0x539**
🌞

### CODE REVIEW

**Comment by ben0x539** [comment]
Sorry, I haven't really used github actions before and I don't know how to find out what's wrong.

**Comment by ehuss** [comment]
The linkcheck script is a little out-of-sync with the latest nightly docs, it should get resolved after the next nightly is released (~7 hours from now).

**Comment by Havvy** [comment]
Is there a way to re-run style checks?

**Comment by ehuss** [comment]
@Havvy Not sure if you have "write" permissions, but if you do you can click on the "Details" link for the Actions run, and then in the upper-right corner is a drop-down to re-run an action.

I re-ran this, but it ran into another error.  It will need to be rebased on latest master to pass.

**Review by ehuss — APPROVED** [review]
I'm sorry for the delay, this got lost in my queue.   Thanks for the help!

**Pull request merged**
