### PR TITLE
Metavariables can be keywords

### PR DESCRIPTION
**Pull request by jonas-schievink**

### CODE REVIEW

**Comment by ehuss** [comment]
Thanks!  Do you happen to know the history here?  It looks like this changed in 1.17 (though there weren't any notes about it).  I'm guessing it was via https://github.com/rust-lang/rust/pull/39419?

It looks like this also allows raw identifiers.  Example:

```rust
macro_rules! foo {
    ($r#fn:expr) => {$r#fn};
}
```

which seems a little odd to me. 🤷   Maybe the "identifiers" page should have a production for whatever "ident or keyword or raw keyword" should be called?

Dunno if this is actually intended.

**Comment by jonas-schievink** [comment]
I have no idea about the history here, sorry. I just noticed that rust-analyzer does some gymnastics to also allow keywords here, and realized that rustc also allows them.

**Comment by jonas-schievink** [comment]
> Maybe the "identifiers" page should have a production for whatever "ident or keyword or raw keyword" should be called?

Is there any place in Rust where a normal ident is allowed but a raw ident isn't?

**Comment by ehuss** [comment]
> Is there any place in Rust where a normal ident is allowed but a raw ident isn't?

[`LIFETIME_OR_LABEL`](https://doc.rust-lang.org/nightly/reference/tokens.html?highlight=lifetime_or_label#lifetimes-and-loop-labels)

**Comment by mattheww** [comment]
This change was later made in #1130.

**Comment by ehuss** [comment]
Indeed, I think this can be closed, thanks!

**Pull request closed without merging**
