### PR TITLE
Add `expr_2021` macro fragment specifier

### PR DESCRIPTION
**Pull request by ehuss**
Draft pending stabilization of 2024.

Tracking issue: https://github.com/rust-lang/rust/issues/123742

### CODE REVIEW

**Review by traviscross — APPROVED** [review]
Looks right to me.  We'll probably want to add a commit to sort the block of links at the end when merging.

**Comment by ehuss** [comment]
@mattheww Are you suggesting it should be this?

```diff
-  * FOLLOW(expr) = FOLLOW(stmt) =  {`=>`, `,`, `;`}`.
+  * FOLLOW(expr) = FOLLOW(expr_2021) = FOLLOW(stmt) =  {`=>`, `,`, `;`}`.
```

**Comment by mattheww** [comment]
Yes, I think that's how it works.

**Comment by ehuss** [comment]
Thanks! Yea, that makes sense to me.

**Comment by ehuss** [comment]
Merging now that https://github.com/rust-lang/rust/pull/129972 has stabilized.

**Pull request merged**
