### PR TITLE
Clarify rule for end-of-line backslashes in strings

### PR DESCRIPTION
**Pull request by bgeron**

### CODE REVIEW

**Comment by ehuss** [comment]
I think I can see how it can be confusing due to the use of commas, but I think the original intent is: There is a preceding clause which establishes *when* a continuation happens ("when an unescaped `U+005C` character (`\`) occurs immediately before the line-break") and then lists 3 things that are ignored:

1. The backslash.
2. The linebreak.
3. The whitespace at the beginning of the next line.

Reading it that way, this change seems to remove number 2, which seems wrong.  Perhaps it can be rewritten to be clearer?  Maybe a simple change like this?

```diff
 when an unescaped `U+005C` character (`\`) occurs immediately before the
-line-break, the `U+005C` character, the line-break, and all whitespace at the
+line-break, then the `U+005C` character, the line-break, and all whitespace at the
 beginning of the next line are ignored. Thus `a` and `b` are equal:

```

**Comment by bgeron** [comment]
Great find Eric! Integrated your suggestion and changed the PR title.

**Comment by bgeron** [comment]
Can I just say how happy I am that the Rust community likes to clarify and make small improvements to things, as opposed to other communities with slow processes where things don't get fixed and everyone just accepts the mild snafus

♥

**Comment by bgeron** [comment]
Ready to be merged, I think!

**Pull request merged**
