### PR TITLE
dont use stdcall on x86_64 where it is not a valid ABI

### PR DESCRIPTION
**Pull request by RalfJung**
Unblocks https://github.com/rust-lang/rust/pull/129935

### CODE REVIEW

**Comment by RalfJung** [comment]
@ehuss any preference which ABI to use here? stdcall is 32bit-only, vectorcall is unstable. We could use "system"?

**Comment by ehuss** [comment]
As an alternative, you can just change the `cfg` to be something like `cfg(windows)` (assuming that is "compatible" for stdcall).

**Comment by RalfJung** [comment]
That would make it dead code for CI, but yeah that also works.

**Comment by ehuss** [comment]
> That would make it dead code for CI, but yeah that also works.

I think it's fine. It gets tested in rust-lang/rust under windows.

**Review by ehuss — APPROVED** [review]
Thanks!

**Pull request merged**
