### PR TITLE
Update aarch64 target feature docs to match LLVM

### PR DESCRIPTION
**Pull request by adamgemmell**
https://github.com/rust-lang/stdarch/issues/1432 https://github.com/rust-lang/stdarch/pull/1527

r? @Amanieu

### CODE REVIEW

**Review by Amanieu — APPROVED** [review]
r=me

**Review by ehuss — APPROVED** [review]

**Comment by ehuss** [comment]
Oops, didn't see the upstream hadn't merged, yet. I assume it will, but usually we wait just in case.

**Comment by adamgemmell** [comment]
Both upstreams have been merged, so I think this can be too now. Thanks!

**Comment by ehuss** [comment]
Thanks!

**Pull request merged**
