### PR TITLE
document guarantee about evaluation of associated consts and const blocks

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/112090

I think this has been our intention for a while (ever since https://github.com/rust-lang/rust/issues/67191 landed), but was never properly decided, so it likely needs t-lang FCP.

### CODE REVIEW

**Comment by RalfJung** [comment]
Blocked on https://github.com/rust-lang/rust/issues/124971

**Comment by joshtriplett** [comment]
@rfcbot merge

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Review by ehuss — APPROVED** [review]
Thanks!

**Pull request merged**
